site_name: cbers4asat

theme:
  name:
    "readthedocs"

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [ src ]

nav:
  - Inicio: index.md
  - Instalação: installation.md
  - Guia de Usuário: quickstart.md
  - API Python: api_reference.md
  - Exemplos: examples.md
